# Evaluación I Módulo 2 (sprint 1)
## Ejercicios de NumPy
---
1. Importa la librería de NumPy.

In [2]:
import numpy as np

2. Crea un array de 1 dimension y 10 elementos.

In [3]:
arr10 = np.random.randint(10,30, (10))
print(f'El array creado es: {arr10} y tiene {len(arr10)} elementos')

El array creado es: [24 10 26 23 15 29 29 13 20 11] y tiene 10 elementos


3. Reemplaza todos los números impares por el valor "impar" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.

In [4]:
# una opción sería crear un array vacío y rellenarlo iterando
arr_new = np.empty_like(arr10, dtype=object)
print(f'El array vacío es: \n{arr_new}')

El array vacío es: 
[None None None None None None None None None None]


In [5]:
contador = 0
for i in arr10:
    if i % 2 == 0:
        arr_new[contador] = 'par'
    else:
        arr_new[contador] = 'impar'
    contador += 1
print(f'El array resultado de la sustitución es: \n{arr_new}')

El array resultado de la sustitución es: 
['par' 'par' 'par' 'impar' 'impar' 'impar' 'impar' 'impar' 'par' 'impar']


In [6]:
# otra opción es hacer una copia del array original y sustituir sobre la copia los valores con el método np.where()
arr_new2 = arr10.copy()
arr_new2 = np.where(arr_new2 % 2 != 0, 'impar', 'par') 
print(f'El array resultado de la sustitución es: \n{arr_new2}')

El array resultado de la sustitución es: 
['par' 'par' 'par' 'impar' 'impar' 'impar' 'impar' 'impar' 'par' 'impar']


4. Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.

In [7]:
arr_2_5 = np.reshape(arr_new, (2,5))
print(f'El array creado es: \n{arr_2_5} \nTiene {arr_2_5.shape[0]} filas y {arr_2_5.shape[1]} columnas')

El array creado es: 
[['par' 'par' 'par' 'impar' 'impar']
 ['impar' 'impar' 'impar' 'par' 'impar']] 
Tiene 2 filas y 5 columnas


5. Extrae los elementos comunes de los siguientes arrays  
    ```python
    array1 = np.array([1,2,3,2,3,4,3,4,5,6])
    array2 = np.array([7,2,10,2,7,4,9,4,9,8])
    ```

In [8]:
# creamos los arrays y los printeamos:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])
print(f'El array1 es: {array1}')
print(f'El array2 es: {array2}')

El array1 es: [1 2 3 2 3 4 3 4 5 6]
El array2 es: [ 7  2 10  2  7  4  9  4  9  8]


In [9]:
# obtenemos los elementos comunes y sus índices:
comunes = np.intersect1d(array1, array2, return_indices=True) 
print(f'Los elenetos comunes son {comunes[0]}. \nLa primera posición en la que aparecen en el array1 es: {comunes[1]}. \nLa primera posición en la que aparecen en el array2 es: {comunes[2]}')

Los elenetos comunes son [2 4]. 
La primera posición en la que aparecen en el array1 es: [1 5]. 
La primera posición en la que aparecen en el array2 es: [1 5]


6. Extraed los elementos que están en el array1 pero no en el array2.

In [10]:
solo_arr1 = np.setdiff1d(array1, array2)
print(f'Los elementos que están en el array1 pero no en el array2 son: {solo_arr1}')

Los elementos que están en el array1 pero no en el array2 son: [1 3 5 6]


7. Extraed las posiciones donde tengamos elementos que sean iguales.

In [11]:
# aunque en este caso son pocos elementos por si hubiera más automatizamos la obtención de los resultados en un diccionario:
lista = [array1, array2] # metemos los arrays que nos interesan en una lista
dicc = {} # creamos un diccionario vaciío para guardar los resultados
num_array = 1 # iniciamos el contador de arrays
for arr in lista: # iteramos por la lista de arrays
    contador = 0 # iniciamos el contador para acceder a la posición de cada elemento común a ambos arrays
    for i in comunes[0]:   # iteramos por el array con los elementos comunes
        dicc[f'elemento_{i}_posiciones_en_array{num_array}'] = np.where(arr == comunes[0][contador])[0] # buscamos todas las posiciones de cada elemento común dentro de cada array y las añadimos al diccionario
        contador += 1
    num_array += 1
print(f'Los valores comunes son: {comunes[0]}. A continuación se indican las posiciones que tiene cada valor común en cada uno de los arrays: \n{dicc}')

Los valores comunes son: [2 4]. A continuación se indican las posiciones que tiene cada valor común en cada uno de los arrays: 
{'elemento_2_posiciones_en_array1': array([1, 3]), 'elemento_4_posiciones_en_array1': array([5, 7]), 'elemento_2_posiciones_en_array2': array([1, 3]), 'elemento_4_posiciones_en_array2': array([5, 7])}


8. Cread un array de 3 filas y 5 columnas, con **números enteros** del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.

In [12]:
# creamos el array
arr8 = np.random.randint(0,50, (3,5))
print(f'El array creado es: \n{arr8} \nTiene {arr8.shape[0]} filas y {arr8.shape[1]} columnas y sus elementos son de tipo {arr8.dtype}')

El array creado es: 
[[49 26  4 21 22]
 [33 47 46 13 16]
 [37 39 42 11 24]] 
Tiene 3 filas y 5 columnas y sus elementos son de tipo int64


In [13]:
# extraemos los valores menores que 10 o mayores que 40
arr8_ext = arr8[(arr8 < 10) | (arr8 > 40)]
print(f'Los elementos del array anterior que son menores que 10 o mayores que 40 son: {arr8_ext}')

Los elementos del array anterior que son menores que 10 o mayores que 40 son: [49  4 47 46 42]


9. Cread un array de 5x3 con **números decimales** aleatorios entre el 5 y el 10.

In [14]:
arr_float = np.random.uniform(5,10, size=(5,3))
print(f'El array creado es: \n{arr_float} \nTiene {arr_float.shape[0]} filas y {arr_float.shape[1]} columnas y sus elementos son de tipo {arr_float.dtype}')

El array creado es: 
[[9.01115633 7.26867479 7.45125622]
 [6.88455915 6.5871542  8.48094462]
 [7.17180359 9.18493017 8.88182855]
 [9.99119071 9.03197779 6.06759963]
 [9.14236385 7.23287417 8.84948378]] 
Tiene 5 filas y 3 columnas y sus elementos son de tipo float64


10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20
    - Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas

In [15]:
# creamos el array con las características solicitadas
arr_3d = np.random.randint(1,20, size=(2,4,7))
print(f'El array creado es: \n{arr_3d} \nTiene {arr_3d.shape[0]} matrices {arr_3d.shape[1]} filas y {arr_3d.shape[2]} columnas')

El array creado es: 
[[[ 5  7 17  9 10 12 13]
  [ 8  2 19  1 15 18  8]
  [ 2  9  5  5 17 15  9]
  [15  4 18  1 14 12 11]]

 [[18  4 15  5  3  2 11]
  [11 12 12  4  3  3  7]
  [ 8  6  9 10  1 14 15]
  [18 18 19 16  9 18  5]]] 
Tiene 2 matrices 4 filas y 7 columnas


In [16]:
# trasponemos el array para que tenga 4 matrices, 7 filas y 2 columnas:
arr_3dt = np.transpose(arr_3d, (1,2,0))
print(f'El array creado tiene {arr_3dt.shape[0]} matrices {arr_3dt.shape[1]} filas y {arr_3dt.shape[2]} columnas y es el siguiente: \n{arr_3dt}')

El array creado tiene 4 matrices 7 filas y 2 columnas y es el siguiente: 
[[[ 5 18]
  [ 7  4]
  [17 15]
  [ 9  5]
  [10  3]
  [12  2]
  [13 11]]

 [[ 8 11]
  [ 2 12]
  [19 12]
  [ 1  4]
  [15  3]
  [18  3]
  [ 8  7]]

 [[ 2  8]
  [ 9  6]
  [ 5  9]
  [ 5 10]
  [17  1]
  [15 14]
  [ 9 15]]

 [[15 18]
  [ 4 18]
  [18 19]
  [ 1 16]
  [14  9]
  [12 18]
  [11  5]]]
